export default Object.freeze({
  ROOT: '/',
  HOME: '/home',
  LOGIN: '/login',
  OTP: '/otp',
  CATEGORY: 'category',
  CATEGORIES: 'categories',
  ID: ':id',
  BOOK: 'book',
  USER: 'user',
  PERSONAL: '/personal',
  AUTHOR: 'author',
  AUTHORS: 'authors',
  READER: 'readers',
  NEW: 'new',
  FORGET_PASSWORD: '/forget-password',
  RESET_PASSWORD: '/reset-password',
  SIGN_UP: '/sign-up',
  ALL: 'all',
});
