export default Object.freeze({
  ROOT: '/',
  HOME: '/home',
  LOGIN: '/login',
  OTP: '/otp',
  CATEGORY: 'category',
  ID: ':id',
  BOOK: 'book',
  USER: 'user',
  PERSONAL: '/personal',
  AUTHOR: 'author',
  NEW: 'new',
  FORGET_PASSWORD: '/forget-password',
  RESET_PASSWORD: '/reset-password',
});
