# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Book reader client app CI

on:
  push:
    branches: [ "master" ]

jobs:
  client:
    uses: ./.github/workflows/node-run.yml
    with:
      working-directory: ./book_client
  
  api:
    uses: ./.github/workflows/node-run.yml
    with:
        working-directory: ./book-api
