name: Nodejs run

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: book_client/package-lock.json
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm test --if-present
